### PR TITLE
[Fix #46] support multi-indices query with compatible mappings. Give …

### LINKED ISSUE #46: VerificationException: When using multiple indices, the mappings must be identical.
I'm trying to run SQL queries on an index alias (e.g. _select field from myindex-*_) and my indexes are daily (so I have myindex-2019-04-01, etc.).

For some of the indexes, additional fields have been added and dynamic field mapping has updated the mapping, resulting on myindex-2019-04-01 having less fields compared to myindex-2019-04-02 for example.

When running SQL queries, elasticsearch is complaining with:

> VerificationException: When using multiple indices, the mappings must be identical.

even though the SQL query is not using the fields that are different between the indexes.
Is there any way to relax the strictness of all mappings having to be identical?

if I run:

> select myfield from myindex*

and the mapping for _myfield_ is the same on all indexes matching myindex*, do we really want to enforce the whole mapping is identical? I'm not seeing the benefit of that.
even if some indexes do not contain _myfield_, wouldn't it be better to just return an empty value for such column instead of not allowing the request at all?

### PR DESCRIPTION
**Pull request by zhongnansu**
*Issue #, if available:*#46

*Description of changes:*
1. Previously we were throwing VerificationException if the mappings were non-identical for expanded indices. Even though the fields of the indices with extra mappings are not used we were throwing VerificationException.
2. For fields with same name but different mappings across indices, we will throw VerificationEXception highlighting the differences in mapping causing this exception. 

*Test:* 
Passes existing Gradle build and tests. Added new integration tests.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java [hunk 1]
```diff
@@ -35,11 +35,7 @@
 import org.json.JSONObject;
 
 import java.io.IOException;
-import java.util.Arrays;
-import java.util.Collection;
-import java.util.List;
-import java.util.Map;
-import java.util.Objects;
+import java.util.*;
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java]: Please do not use star imports, it makes it more difficult to quickly identify where each of the used types is coming from. You can update IntelliJ's setting to not auto-convert to star.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java [hunk 2]
```diff
@@ -399,6 +395,12 @@ public FieldMappings(MappingMetaData mappings) {
             fieldMappings = mappings.sourceAsMap();
         }
 
+        public FieldMappings(Map<String, Map<String, Object>> map) {
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java]: Please add documentation for public methods, especially for the cases like this one, where it's not obvious (e.g.  why we need the second constructor).

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 3]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
+                                 flatMap(typeMappings -> typeMappings.allMappings().stream()).
+                                 collect(Collectors.toSet());
 
-        if (isMappingOfAllIndicesDifferent()) {
-            return false;
-        }
+        FieldMappings fieldMappings = null;
+
+        if (set.size() > 1) {
+            Map<String, Map<String, Object>> map = new LinkedHashMap<>();
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: please use more descriptive names for variables.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 4]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
     }
 
-    public boolean hasIdenticalMappings(TermFieldScope scope, Map<String, String> indexToType) {
+    public void checkMappingCompatibility(TermFieldScope scope, Map<String, String> indexToType) {
         if (scope.getMapper().isEmpty()) {
             throw new VerificationException("Unknown index " + indexToType.keySet());
         }
+        // Collect all FieldMappings into hash set and ignore index/type names. set.size > 1 means FieldMappings NOT unique,
+        // needs further compatibility check
+        Set<FieldMappings> set = curScope().getMapper().allMappings().stream().
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: use more descriptive names, the identifier should represent what the underlying object's functional purpose is, not what type it is of.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 5]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
-        }
+        FieldMappings fieldMappings = null;
+
+        if (set.size() > 1) {
+            Map<String, Map<String, Object>> map = new LinkedHashMap<>();
+
+            for (FieldMappings f : set) {
+                Map<String, Map<String, Object>> m = f.data();
+
+                for (Map.Entry<String, Map<String, Object>> e : m.entrySet()) {
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: ideally, we should not have variables with names `m`, `e`, unless it's a simple index in a `for` loop, or an exception in a `catch` statement, maybe a couple more exceptions.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 6]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
+                    String fieldName = e.getKey();
+                    Map<String, Object> fieldMappingValue = e.getValue();
+
+                    if (!map.containsKey(fieldName)) {
+                        map.put(fieldName, fieldMappingValue);
+                    } else {
+                        // check if types are same
+                        if (!fieldMappingValue.equals(map.get(fieldName))) {
+                           // TODO: Merge mappings if they are compatible, like text and text/keyword to text/keyword.
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: I think merge should take the intersection, not the union. Because otherwise one can use properties of a mapping for an index that does not actually have it. Also, please open an issue to track it, I don't think we have a clearly defined process for resolving TODOs.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 7]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
 
+                            String firstFieldType= new JSONObject(fieldMappingValue).toString().replaceAll("\"", "");
+                            String secondFieldType = new JSONObject(map.get(fieldName)).toString().replaceAll("\"", "");
+
+                            String exceptionReason = String.format("Cannot use field [%s] " +
+                                            "due to ambiguities being mapped as incompatible types: [%s] and [%s] ",
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: not sure what 'ambiguities' refers to here, but I think the message itself is ambiguous. +Ideally we provide the index name also (but that's not a blocker). Maybe just say `"Field [%s] has different different mappings in the specified indices. Index [%s] - mapping: [%s], index [%s] - mapping [%s]"`. If you want to omit index names, maybe something like `"Different mappings are not allowed for the same field: found [%s] and [%s]"`. Finally, please use `Locale.ROOT` with `String.format`.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 3 above)
Comment (arsen-es) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: seems you are not using any of the LinkedList features of this map, so just make it a `HashMap`

File: src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java [hunk 8]
```diff
@@ -24,11 +24,7 @@
 import java.io.IOException;
 import java.util.Locale;
 
-import static com.amazon.opendistroforelasticsearch.sql.esintgtest.TestsConstants.TEST_INDEX_ACCOUNT;
-import static com.amazon.opendistroforelasticsearch.sql.esintgtest.TestsConstants.TEST_INDEX_BANK;
-import static com.amazon.opendistroforelasticsearch.sql.esintgtest.TestsConstants.TEST_INDEX_BANK_TWO;
-import static com.amazon.opendistroforelasticsearch.sql.esintgtest.TestsConstants.TEST_INDEX_DOG;
-import static com.amazon.opendistroforelasticsearch.sql.esintgtest.TestsConstants.TEST_INDEX_ONLINE;
+import static com.amazon.opendistroforelasticsearch.sql.esintgtest.TestsConstants.*;
```
Comment (arsen-es) [inline src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: no star imports please

File: src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java [hunk 9]
```diff
@@ -102,19 +100,28 @@ public void testNonResolvingIndexPatternWithNonExistingIndex() throws IOExceptio
     }
 
     @Test
-    public void testNonIdenticalMappings() throws IOException {
+    public void testNonCompatibleMappings() throws IOException {
         try {
-            explainQuery(String.format(Locale.ROOT, "SELECT firstname, birthdate FROM %s, %s " +
-                            "WHERE firstname = 'Leo' OR male = 'true'",
-                    TEST_INDEX_BANK, TEST_INDEX_ONLINE));
+            explainQuery(String.format(Locale.ROOT, "SELECT * FROM %s, %s ",
```
Comment (arsen-es) [inline src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: please add `Assert.fail()` after this line (in the `try` block), otherwise if no exception is thrown your test will still pass.

File: src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java [hunk 10]
```diff
@@ -102,19 +100,28 @@ public void testNonResolvingIndexPatternWithNonExistingIndex() throws IOExceptio
...
-            assertThat(entity, containsString("When using multiple indices, the mappings must be identical"));
+            assertThat(entity, containsString("dog_name"));
+            assertThat(entity, containsString("{type:text,fields:{keyword:{type:keyword,ignore_above:256}}}"));
+            assertThat(entity, containsString("{type:text,fielddata:true}"));
             assertThat(entity, containsString("\"type\": \"VerificationException\""));
         }
     }
 
+    @Test
+    public void testCompatibleMappings() throws IOException {
```
Comment (arsen-es) [inline src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: the name is misleading, since we don't check compatibility but equality, I'd rename this to `testEqualFieldMappings` or something alike. When that TODO is resolved and we really check compatibility, then we'll need to add more tests for that.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 11]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
             );
     }
 
-    public boolean hasIdenticalMappings(TermFieldScope scope, Map<String, String> indexToType) {
+    public void checkMappingCompatibility(TermFieldScope scope, Map<String, String> indexToType) {
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: can this method be `private`?

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 12]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
+        Set<FieldMappings> set = curScope().getMapper().allMappings().stream().
+                                 flatMap(typeMappings -> typeMappings.allMappings().stream()).
+                                 collect(Collectors.toSet());
 
-        if (isMappingOfAllIndicesDifferent()) {
-            return false;
-        }
+        FieldMappings fieldMappings = null;
+
+        if (set.size() > 1) {
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: NP: this `if` block is too large and too nested, I think extracting out a pieces/pieces into smaller private methods would help with readability.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 7 above)
Comment (dai-chen) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: > not sure what 'ambiguities' refers to here, but I think the message itself is ambiguous. +Ideally we provide the index name also (but that's not a blocker). Maybe just say `"Field [%s] has different different mappings in the specified indices. Index [%s] - mapping: [%s], index [%s] - mapping [%s]"`. If you want to omit index names, maybe something like `"Different mappings are not allowed for the same field: found [%s] and [%s]"`. Finally, please use `Locale.ROOT` with `String.format`.

Agree. Maybe we can make this easier, just give index name, field name/type and expected type. I think these should be sufficient for customer to understand what's happening.

@arsen-es btw, we may need a utility method if you think passing `Locale.ROOT` is required for each call to `String.format`.

Comment (abbashus) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: @arsen-es The message structure is taken from existing ElasticSearch SQL Exception

```
{
  "error": {
    "root_cause": [
      {
        "type": "verification_exception",
        "reason": "Found 1 problem(s)\nline 1:8: Cannot use field [field_1] due to ambiguities being mapped as [2] incompatible types: [text] in [test_1], [long] in [test_2]"
      }
    ],
    "type": "verification_exception",
    "reason": "Found 1 problem(s)\nline 1:8: Cannot use field [field_1] due to ambiguities being mapped as [2] incompatible types: [text] in [test_1], [long] in [test_2]"
  },
  "status": 400
}
```

Since we have already stripped out index names, we can't add index name to exception message.

Comment (abbashus) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: @dai-chen Since we can have multiple indices wit same field name but different mappings, We cannot identify a expected type. Any of them could be expected depending on users case.

Comment (dai-chen) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: > @dai-chen Since we can have multiple indices wit same field name but different mappings, We cannot identify a expected type. Any of them could be expected depending on users case.

Sure. Sorry I meant the type in `fieldMappingValue` and `map.get(fieldName)` which we're comparing.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 3 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: > seems you are not using any of the LinkedList features of this map, so just make it a `HashMap`

I created this as LinkedHashMap because all the fieldMappings we generated elsewhere are created this way, and I think it would be better to keep it the same data type to avoid mismatch issue.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java (hunk 1 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java]: will fix this and the similar issue in other files. Thanks.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 11 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: Yes, it can. But I saw many methods that has only one usage within the same class are given public access identifier(even the one I deleted(hasIdenticalMappings), I wonder if you did this on purpose for future use.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 3 above)
Comment (arsen-es) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: the fact is you use only `put` and `contains`, and for that you don't need any ordering (which is what `LinkedHashMap` adds to `HashMap`)

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 7 above)
Comment (arsen-es) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: @abbashus The current message says we are "mapping the ambiguities", which is incorrect. So let's fix it (I didn't mean you introduced the bad message).

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 11 above)
Comment (arsen-es) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: `public` methods are meant to be called from outside, if there is no need for that ,the method should not be `public`. In this case `private` is the best option, since this is just internal implementation.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java (hunk 2 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java]: The constructor signature is self-documenting. We are inititalizing a class member using that.

Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/esdomain/LocalClusterState.java]: will fix the name of parameter from map to mapping

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: Good point.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 11 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: That makes sense. Fixed.

File: src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java (hunk 10 above)
Comment (zhongnansu) [reply src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: We are not checking equality here. We are checking if the mappings for the same field name are equal or one index has extra mapping not present in others, we should not throw an exception. Does `testMappingsNotDifferent` sounds good?

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 4 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: changed to mappingSet

File: src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java (hunk 8 above)
Comment (zhongnansu) [reply src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: Fixed.

File: src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java (hunk 9 above)
Comment (zhongnansu) [reply src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: Good point. Added that as you pointed out.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 3 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: That makes sense. Will change to hashMap

File: src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java (hunk 10 above)
Comment (arsen-es) [reply src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: I think that's what the code here does - check that for the relevant fields the mappings are equal. As I mentioned, the //TODO comment you put on TermFieldRewriter.java#244 is to support the compatibility, but with current change it's just equality. I just want the test name to reflect that.

Comment (zhongnansu) [reply src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TermQueryExplainIT.java]: I misunderstood you. I thought you want sth like `testIdenticalMapping` which we already have.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 12 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: Fixed by wrapping some logic into a method called getMergedMapping

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 5 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: Get rid of e using foreach with lambda. For m, I can't think of a better name, any suggestion?

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 13]
```diff
@@ -72,10 +75,11 @@ public boolean visit(MySqlSelectQueryBlock query) {
         Map<String, String> indexToType = new HashMap<>();
         collect(query.getFrom(), indexToType, curScope().getAliases());
         curScope().setMapper(getMappings(indexToType));
-        if ((this.filterType == TermRewriterFilter.COMMA || this.filterType == TermRewriterFilter.MULTI_QUERY)
-            && !hasIdenticalMappings(curScope(), indexToType)) {
-            throw new VerificationException("When using multiple indices, the mappings must be identical.");
+
+        if ((this.filterType == TermRewriterFilter.COMMA || this.filterType == TermRewriterFilter.MULTI_QUERY)) {
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: remove the extra pair of parentheses

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 14]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
             );
     }
 
-    public boolean hasIdenticalMappings(TermFieldScope scope, Map<String, String> indexToType) {
+    private void checkMappingCompatibility(TermFieldScope scope, Map<String, String> indexToType) {
         if (scope.getMapper().isEmpty()) {
             throw new VerificationException("Unknown index " + indexToType.keySet());
         }
+        // Collect all FieldMappings into hash set and ignore index/type names. set.size > 1 means FieldMappings NOT unique,
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: I think this comment is redundant, it just tells what the following code does, and that in its turn is pretty straightforward.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 15]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
+    private void getMergedMapping(String fieldName, Map<String, Object> fieldMappingValue , Map<String, Map<String, Object>> mergedMapping){
+
+        if (!mergedMapping.containsKey(fieldName)) {
+            mergedMapping.put(fieldName, fieldMappingValue);
+        } else {
+            // check if types are same
+            if (!fieldMappingValue.equals(mergedMapping.get(fieldName))) {
+                // TODO: Merge mappings if they are compatible, like text and text/keyword to text/keyword.
+
+                String firstFieldType= new JSONObject(fieldMappingValue).toString().replaceAll("\"", "");
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: missing space before `=`.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 16]
```diff
@@ -210,19 +214,53 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
+                String secondFieldType = new JSONObject(mergedMapping.get(fieldName)).toString().replaceAll("\"", "");
+
+                String exceptionReason = String.format(Locale.ROOT,"Cannot use field [%s] " +
+                                "due to ambiguities being mapped as incompatible types: [%s] and [%s] ",
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: message still not fixed

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 15 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: will fix that, thx.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 14 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: will get rid of it.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 13 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: will fix that, thx.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 16 above)
Comment (abbashus) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: I don't see any problem with the message. The message is in alignment with xpack exception. What is that you don't understand or seems incorrect to you. If you have good suggestion please provide it.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 6 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: The todo here is only dealing with one case I met while testing, which is the text(or other type) and text(or other type).keyword. It doesn't affect solving this issue. Sure, will create another issue to track it.

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java (hunk 16 above)
Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: > message still not fixed

Okay, we will use the followoing meassage as suggested `Different mappings are not allowed for the same field[%s]: found [%s] and [%s]

File: src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java [hunk 17]
```diff
@@ -210,19 +214,52 @@ public boolean isValidIdentifierForTerm(SQLIdentifierExpr expr) {
...
+        } else {
+            fieldMappings = curScope().getMapper().firstMapping().firstMapping();
+        }
         // We need finalMapping to lookup for rewriting
-        FieldMappings fieldMappings = curScope().getMapper().firstMapping().firstMapping();
         curScope().setFinalMapping(fieldMappings);
-        return true;
+    }
+
+    private void getMergedMapping(String fieldName, Map<String, Object> fieldMappingValue , Map<String, Map<String, Object>> mergedMapping){
```
Comment (arsen-es) [inline src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: Sorry, missed this one, if the function name is `getSomething`, then it should return something, maybe `verifySingleFieldMapping` or whatever better name you think of.

Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: I was also thinking about this. The method is actually constructing the mapping we want to use. It's adding content to the Map `mergedMapping`, which is passed as a parameter.  Does `mergeMapping` sound like a good method name to you?

Comment (arsen-es) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: I think adding a new mapping to that merged map is just a side effect of this method, not the main function, so I am more inclined to assert the verification part in the name.

Comment (zhongnansu) [reply src/main/java/com/amazon/opendistroforelasticsearch/sql/rewriter/matchtoterm/TermFieldRewriter.java]: Got you. Fixed as `verifySingleFieldMapping`
